name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Restore dependencies
      run: npm run ci
    - name: Run npm build
      run: npm run build -- --prod
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Restore dependencies
        run: npm run ci
      - name: Run unit test
        run: npm run test -- --code-coverage --watch=false
